# baseURL = "http://rogueliketutorials.com/"
baseURL = "https://qkzk.github.io/"
languageCode = "en"
title = "Tutoriel Roguelike"

theme = "hugo-bootstrap"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[languages.en]
  languageName = "English"

  copyright = "Dernière mise à jour le 24 juillet 2019"

  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.main]]
    url = "/tutorials/tcod/"
    name = "Tutoriel TCOD"
    weight = 2
  [[languages.en.menu.main]]
    url = "/about/"
    name = "A propos"
    weight = 3

[params]
  mainSections = ["post"]

  [params.sidebar]
    showRecent = false

  [params.header]
    colorScheme = "dark"
