# baseURL = "http://rogueliketutorials.com/"
baseURL = "/"
languageCode = "fr"
title = "Tutoriel Roguelike"

theme = "hugo-bootstrap"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[languages.fr]
  languageName = "Francais"

  copyright = "Dernière mise à jour le 24 juillet 2019"

  [[languages.fr.menu.main]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.fr.menu.main]]
    url = "/tutoriels/tcod/"
    name = "Tutoriel TCOD"
    weight = 2
  [[languages.fr.menu.main]]
    url = "/apropos/"
    name = "A propos"
    weight = 3

[params]
  mainSections = ["post"]

  [params.sidebar]
    showRecent = false

  [params.header]
    colorScheme = "dark"
